services:
  app:
    build: .
    networks:
      - triagem_service
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
  db:
    image: mariadb:10.6
    networks:
      - triagem_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  triagem_service:
    driver: "bridge"